name: Production AWS S3+Cloudfront Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Authenticate AWS session
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://${{ secrets.BUCKET_NAME }} --delete

    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id "${{ secrets.DISTRIBUTION_ID_TO_INVALIDATE }}" --paths '/*'
