
name: pipeline
on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: high
          
      - name: 'Clean install'
        run: npm ci
        
      - name: 'Build'
        run: npm run build --if-present
        
      - name: 'Lint'
        run: npm lint
 
      - name: 'Authenticate AWS session'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
  
      - name: 'Deploy static site to S3 bucket'
        run: aws s3 sync ./out/ s3://${{ secrets.BUCKET_NAME }} --delete
  
      - name: 'Invalidate Cloudfront cache'
        run: aws cloudfront create-invalidation --distribution-id "${{ secrets.DISTRIBUTION_ID_TO_INVALIDATE }}" --paths '/*'
